using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace EnterpriseWorkflow.Persistence.Oracle.Migrations;

[DbContext(typeof(OracleWorkflowDbContext))]
[Migration("202610010002_InitialOracle")]
public sealed class InitialOracle : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        Sql(migrationBuilder, """
            CREATE TABLE "EW_DEFINITIONS" (
                "DEFINITION_ID" VARCHAR2(128 CHAR) NOT NULL,
                "VERSION" NUMBER(10) NOT NULL,
                "SHA256" CHAR(64 CHAR) NOT NULL,
                "SCHEMA_VERSION" NUMBER(10) NOT NULL,
                "CANONICAL_JSON" CLOB NOT NULL,
                "PUBLISHED_AT_MS" NUMBER(19) NOT NULL,
                CONSTRAINT "PK_EW_DEFINITIONS" PRIMARY KEY ("DEFINITION_ID", "VERSION")
            )
            """);
        Sql(migrationBuilder, """
            CREATE TABLE "EW_INSTANCES" (
                "ID" CHAR(32 CHAR) NOT NULL,
                "DEFINITION_ID" VARCHAR2(128 CHAR) NOT NULL,
                "DEFINITION_VERSION" NUMBER(10) NOT NULL,
                "DEFINITION_SHA256" CHAR(64 CHAR) NOT NULL,
                "STATUS" NUMBER(10) NOT NULL,
                "REVISION" NUMBER(19) NOT NULL,
                "STATE_SCHEMA_VERSION" NUMBER(10) NOT NULL,
                "STATE_JSON" CLOB NOT NULL,
                "BUSINESS_KEY" VARCHAR2(512 CHAR) NULL,
                "CORRELATION_ID" VARCHAR2(512 CHAR) NULL,
                "CREATED_AT_MS" NUMBER(19) NOT NULL,
                "UPDATED_AT_MS" NUMBER(19) NOT NULL,
                CONSTRAINT "PK_EW_INSTANCES" PRIMARY KEY ("ID"),
                CONSTRAINT "FK_EW_INSTANCE_DEFINITION" FOREIGN KEY ("DEFINITION_ID", "DEFINITION_VERSION")
                    REFERENCES "EW_DEFINITIONS" ("DEFINITION_ID", "VERSION")
            )
            """);
        Sql(migrationBuilder, """
            CREATE TABLE "EW_ACTIVATIONS" (
                "ID" CHAR(32 CHAR) NOT NULL,
                "INSTANCE_ID" CHAR(32 CHAR) NOT NULL,
                "NODE_ID" VARCHAR2(128 CHAR) NOT NULL,
                "STATUS" NUMBER(10) NOT NULL,
                "ATTEMPT" NUMBER(10) NOT NULL,
                "ERROR_CODE" VARCHAR2(128 CHAR) NULL,
                CONSTRAINT "PK_EW_ACTIVATIONS" PRIMARY KEY ("ID"),
                CONSTRAINT "FK_EW_ACT_INSTANCE" FOREIGN KEY ("INSTANCE_ID")
                    REFERENCES "EW_INSTANCES" ("ID") ON DELETE CASCADE
            )
            """);
        Sql(migrationBuilder, """
            CREATE TABLE "EW_WORK_ITEMS" (
                "ID" CHAR(32 CHAR) NOT NULL,
                "ACTIVATION_ID" CHAR(32 CHAR) NOT NULL,
                "INSTANCE_ID" CHAR(32 CHAR) NOT NULL,
                "NODE_ID" VARCHAR2(128 CHAR) NOT NULL,
                "STATUS" NUMBER(10) NOT NULL,
                "DUE_AT_MS" NUMBER(19) NOT NULL,
                "OWNER_ID" VARCHAR2(128 CHAR) NULL,
                "GENERATION" NUMBER(19) NOT NULL,
                "LEASE_TOKEN" CHAR(32 CHAR) NULL,
                "LEASE_EXPIRES_AT_MS" NUMBER(19) NULL,
                "CREATED_AT_MS" NUMBER(19) NOT NULL,
                CONSTRAINT "PK_EW_WORK_ITEMS" PRIMARY KEY ("ID"),
                CONSTRAINT "FK_EW_WORK_ACTIVATION" FOREIGN KEY ("ACTIVATION_ID")
                    REFERENCES "EW_ACTIVATIONS" ("ID") ON DELETE CASCADE,
                CONSTRAINT "FK_EW_WORK_INSTANCE" FOREIGN KEY ("INSTANCE_ID")
                    REFERENCES "EW_INSTANCES" ("ID") ON DELETE CASCADE
            )
            """);
        Sql(migrationBuilder, """
            CREATE TABLE "EW_START_RECEIPTS" (
                "RECEIPT_KEY" CHAR(64 CHAR) NOT NULL,
                "INSTALLATION_ID" VARCHAR2(128 CHAR) NOT NULL,
                "COMMAND_TYPE_ID" VARCHAR2(128 CHAR) NOT NULL,
                "ACTOR_PROVIDER_ID" VARCHAR2(128 CHAR) NOT NULL,
                "ACTOR_SUBJECT_ID" VARCHAR2(512 CHAR) NOT NULL,
                "IDEMPOTENCY_KEY" VARCHAR2(128 CHAR) NOT NULL,
                "REQUEST_SHA256" VARCHAR2(64 CHAR) NOT NULL,
                "INSTANCE_ID" CHAR(32 CHAR) NOT NULL,
                "INSTANCE_REVISION" NUMBER(19) NOT NULL,
                "COMMITTED_AT_MS" NUMBER(19) NOT NULL,
                CONSTRAINT "PK_EW_START_RECEIPTS" PRIMARY KEY ("RECEIPT_KEY"),
                CONSTRAINT "FK_EW_RECEIPT_INSTANCE" FOREIGN KEY ("INSTANCE_ID")
                    REFERENCES "EW_INSTANCES" ("ID")
            )
            """);
        Sql(migrationBuilder, """
            CREATE TABLE "EW_AUDITS" (
                "SEQUENCE" NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
                "INSTANCE_ID" CHAR(32 CHAR) NOT NULL,
                "EVENT_TYPE" VARCHAR2(64 CHAR) NOT NULL,
                "REVISION" NUMBER(19) NOT NULL,
                "OCCURRED_AT_MS" NUMBER(19) NOT NULL,
                "ACTOR_PROVIDER_ID" VARCHAR2(128 CHAR) NULL,
                "ACTOR_SUBJECT_ID" VARCHAR2(512 CHAR) NULL,
                CONSTRAINT "PK_EW_AUDITS" PRIMARY KEY ("SEQUENCE"),
                CONSTRAINT "FK_EW_AUDIT_INSTANCE" FOREIGN KEY ("INSTANCE_ID")
                    REFERENCES "EW_INSTANCES" ("ID") ON DELETE CASCADE
            )
            """);
        Sql(migrationBuilder, "CREATE INDEX \"IX_EW_INSTANCE_DEF_STATUS\" ON \"EW_INSTANCES\" (\"DEFINITION_ID\", \"DEFINITION_VERSION\", \"STATUS\")");
        Sql(migrationBuilder, "CREATE INDEX \"IX_EW_ACT_INSTANCE\" ON \"EW_ACTIVATIONS\" (\"INSTANCE_ID\")");
        Sql(migrationBuilder, "CREATE UNIQUE INDEX \"UX_EW_WORK_ACTIVATION\" ON \"EW_WORK_ITEMS\" (\"ACTIVATION_ID\")");
        Sql(migrationBuilder, "CREATE INDEX \"IX_EW_WORK_STATUS_DUE\" ON \"EW_WORK_ITEMS\" (\"STATUS\", \"DUE_AT_MS\")");
        Sql(migrationBuilder, "CREATE INDEX \"IX_EW_WORK_STATUS_LEASE\" ON \"EW_WORK_ITEMS\" (\"STATUS\", \"LEASE_EXPIRES_AT_MS\")");
        Sql(migrationBuilder, "CREATE INDEX \"IX_EW_AUDIT_INSTANCE_SEQ\" ON \"EW_AUDITS\" (\"INSTANCE_ID\", \"SEQUENCE\")");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        Sql(migrationBuilder, "DROP TABLE \"EW_AUDITS\" CASCADE CONSTRAINTS PURGE");
        Sql(migrationBuilder, "DROP TABLE \"EW_START_RECEIPTS\" CASCADE CONSTRAINTS PURGE");
        Sql(migrationBuilder, "DROP TABLE \"EW_WORK_ITEMS\" CASCADE CONSTRAINTS PURGE");
        Sql(migrationBuilder, "DROP TABLE \"EW_ACTIVATIONS\" CASCADE CONSTRAINTS PURGE");
        Sql(migrationBuilder, "DROP TABLE \"EW_INSTANCES\" CASCADE CONSTRAINTS PURGE");
        Sql(migrationBuilder, "DROP TABLE \"EW_DEFINITIONS\" CASCADE CONSTRAINTS PURGE");
    }

    private static void Sql(MigrationBuilder migrationBuilder, string sql) =>
        migrationBuilder.Sql(sql, suppressTransaction: true);
}
