<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>C# authoring SDK for Enterprise Workflow.</Description>
    <RootNamespace>EnterpriseWorkflow.Sdk</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../EnterpriseWorkflow.Abstractions/EnterpriseWorkflow.Abstractions.csproj" />
    <ProjectReference Include="../EnterpriseWorkflow.Core/EnterpriseWorkflow.Core.csproj" />
  </ItemGroup>
</Project>

