<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../samples/LeaveRequest.Module/EnterpriseWorkflow.LeaveRequest.Module.csproj" ReferenceOutputAssembly="false" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/EnterpriseWorkflow.Extensions/EnterpriseWorkflow.Extensions.csproj" />
    <ProjectReference Include="../Fixtures/ApprovalModule.V1/ApprovalModule.V1.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../Fixtures/ApprovalModule.V2/ApprovalModule.V2.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
