<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Internal profile authorization and local/Active Directory security providers.</Description>
    <RootNamespace>EnterpriseWorkflow.Security</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../EnterpriseWorkflow.Security.Abstractions/EnterpriseWorkflow.Security.Abstractions.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="System.DirectoryServices.Protocols" />
  </ItemGroup>
</Project>
